name: Auto Label Conflicts

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  auto-Label:
    if: github.repository == 'NiladriHazra/Open-Fiesta'
    runs-on: ubuntu-latest
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v3
        with:
          conflict_label_name: 'Merge Conflict'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_retries: 5
          wait_ms: 15000
          detect_merge_changes: false
          conflict_comment: |
            Conflicts have been detected against the base branch. 
            Please resolve merge conflicts before merging.
